using Nashet.FlagGeneration;
using Nashet.GameplayView;
using Nashet.Map.GameplayControllers;
using Nashet.Map.Utils;
using Nashet.MapMeshes;
using Nashet.UnitSelection;
using QPathFinder;
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace Nashet.Map.Examples
{
	public class UnitsController : MonoBehaviour
	{
		[SerializeField] UnitView unitPrefab;
		[SerializeField] MapGenerator mapGenerator;
		[SerializeField] private int initialPoolSize = 10;

		private MonoObjectPool<UnitView> unitPool;
		private Dictionary<Collider, UnitView> unitsLookup = new();
		private float unitMovementRate = 0.15f;

		private IEnumerator Start()
		{
			yield return new WaitUntil(() => mapGenerator.IsReady);
			Initialize();
		}

		private void Initialize()
		{
			unitPool = new MonoObjectPool<UnitView>(unitPrefab, initialPoolSize);
			var cameraHolder = Camera.main;

			var selectionComponent = cameraHolder.gameObject.GetComponent<SelectionComponent>();
			selectionComponent.OnEntitySelected += UnitSelectedHandler;
			selectionComponent.OnEntitySelected += ProvinceSelectedHandler;
			selectionComponent.OnMultipleEntitiesSelected += MultipleSelectionHandler;

			CreateUnitsForTest();
			SelectionComponent.ArmiesGetter = (int arg) => AllArmiesColliders();
			InvokeRepeating(nameof(MoveUnits), 0f, unitMovementRate);
		}

		private IEnumerable<Collider> AllArmiesColliders()
		{
			foreach (var item in unitsLookup.Keys)
				yield return item;
		}

		private void MoveUnits()
		{
			foreach (var unit in unitsLookup.Values)
			{
				if (unit.HasPath)
				{
					unit.Move();
				}
			}
		}

		private void ProvinceSelectedHandler(SelectionData data, int buttonNumber)
		{
			if (data == null)
			{
				DeselectAllUnits();
				return;
			}

			if (data.SingleSelection.gameObject.name == "Body")
				return;

			if (buttonNumber == 0)
				DeselectAllUnits();

			if (buttonNumber != 1)
			{
				return;
			}

			foreach (var unit in unitsLookup.Values)
			{
				if (!unit.IsSelected)
					continue;

				var province = Province.AllProvinces[unit.ProvinceId];
				var targetProvinceId = ProvinceMesh.GetIdByCollider(data.SingleSelection).Value;
				var targetProvince = Province.AllProvinces[targetProvinceId];
				PathFinder.instance.FindShortestPathOfNodes(province.Node.autoGeneratedID, targetProvince.Node.autoGeneratedID, Execution.Synchronous, (path) =>
			{
				unit.SetPath(path);
			});
			}
		}

		private void MultipleSelectionHandler(SelectionData data, int buttonNumber)
		{
			if (data == null)
				return;

			if (buttonNumber != 0)
				return;

			DeselectAllUnits();
			foreach (var item in data.MultipleSelection)
			{
				if (unitsLookup.TryGetValue(item, out var unit))
				{
					unit.Select();
				}
			}
		}

		private void UnitSelectedHandler(SelectionData data, int buttonNumber)
		{
			if (data == null)
				return;

			if (buttonNumber != 0)
				return;

			if (unitsLookup.TryGetValue(data.SingleSelection, out var unit))
			{

				if (GetSelectedUnitsCount() >= 2)
				{
					DeselectAllUnits();
					unit.Select();
					return;
				}

				if (unit.IsSelected)
				{
					unit.Deselect();
					return;
				}
				else
					DeselectAllUnits();

				unit.Select();
			}
		}

		private int GetSelectedUnitsCount()
		{
			var count = 0;
			foreach (var item in unitsLookup.Values)
			{
				if (item.IsSelected)
					count++;
			}
			return count;
		}

		private void DeselectAllUnits()
		{
			foreach (var unit in unitsLookup.Values)
			{
				unit.Deselect();
			}
		}

		private void CreateUnitsForTest()
		{
			foreach (var item in Country.AllCountries)
			{
				var texture = FlagGenerator.Generate(128, 128);
				Sprite sprite = Sprite.Create(texture, new Rect(0, 0, 128, 128), new Vector2(1f, 1f));
				var unit = unitPool.Get();
				unit.gameObject.transform.SetParent(transform);
				unit.Initialize(item.Capital.Position, item.Capital.Id, sprite);
				unitsLookup.Add(unit.GetCollider(), unit);
			}
		}
	}
}